### ISSUE TITLE
Question on Ticket HASH

### ISSUE THREAD

**Issue by mmellottsam** [LifeStack-DEV/lifestack-dev.github.io#2]
I've been playing around with your helpdesk ticketing sheet on Google and I've noticed when the page is refreshed that the TicketNum does not stay the same.  It is appearing to re-create a new ticket number for each issue when the sheet\page is refreshed.  Any input would be appreciated.

**Comment by thiscouldbejd** [comment]
Hi - thanks for raising the issue!

So, I think (and correct me if I have got this wrong) that the 'ticket code' - e.g. Column A on the ISSUES sheet is re-calculating to a different value each time? The HASH function (GET_HASH_CODE) is an attempt to assign a unique value to a forms response row - and keep it (relatively) immutable (e.g. doesn't change). This is so replies / actions on an 'issue / ticket' can be correctly indexed to the right row / issue.

The way the hash is generated is by combining the TIMESTAMP of the form response row (Column F) and the EMAIL address of the respondent (Column G). This should always be the same - provided the underlying data isn't changing.

Are you able to check that those two values are not changing? I _suspect_ (although I have not verified this yet) that if you are allowing users to edit their responses in forms - it is possible the timestamp value will change to the date/time of update - rather than when it was first created / reported?

Happy to dig in further if this isn't the case, or try to think up another way of doing this if needed :)

**Comment by mmellottsam** [comment]
Hi JD,

Thank you for getting back to me.  You are correct, Column A is what is changing.  I have confirmed the timestamp and user code\email is not changing from one day to the next and I have the form locked so they are not allowed to edit their ticket are submitted.  They are required to create a new form entry\ticket for all communications.
Yesterday it was working and we had all the same tickets created in “Completed” status – this morning when we opened the ticketing sheet all the tickets had different ID in Column A and the status for all tickets were set back to “Open”
I have been able to fix the current issue, by coping the ticket number from Column A on the LOG sheet and pasting it in the Issues sheet in Column A.
I just have some concerns moving forward, if we start to use this live with multiple entries per day, what might happen.

Any input would be helpful and please do not rewrite your examples for me.  Just looking for some input and thoughts….
Thank you in advance for your time and input.


Thanks,
Mickie


Mickiah Mellott, ADIT
IT Manager

[sam new logo - llc 2]
3501 Concord Road, Suite 350, York, PA 17402
Direct Office:  717-699-7041

www.StorageAssetManagement.com<http://www.storageassetmanagement.com/>
[cid:image003.jpg@01CE0F5F.BA92B690]<http://www.facebook.com/StorageAssetManagementInc?ref=hl>[cid:image001.jpg@01CE0F5F.BA92B690]<https://twitter.com/#!/StorageAssetMgt>[cid:image008.jpg@01CD76EE.8E8C0F10]<http://www.linkedin.com/company/storage-asset-management-inc>

**Comment by thiscouldbejd** [comment]
Hi Mickie,

Thanks for coming back to me - and thanks for the info. I completely understand what you are saying - but I can't (at the moment) seem to re-create what is happening with my development copy. You mention that the codes changed overnight, so obviously I may need to wait until tomorrow to see if I can get it to do the same! :)

If you are just currently _testing_ it out, does that mean you don't have any private / confidential data in there? If so, would be happy to have a look at your sheet if that would help - as I might be able to spot something in there!

Yours,

JD

**Comment by mmellottsam** [comment]
Hi JD,

Since I’ve copied all the ticket number manually, things seem to be working.  Possible glitch in Google sheets?!?
Thank you so much for your input – we think we will begin using this full time now.


Thanks,
Mickie


Mickiah Mellott, ADIT
IT Manager

[sam new logo - llc 2]
3501 Concord Road, Suite 350, York, PA 17402
Direct Office:  717-699-7041

www.StorageAssetManagement.com<http://www.storageassetmanagement.com/>
[cid:image003.jpg@01CE0F5F.BA92B690]<http://www.facebook.com/StorageAssetManagementInc?ref=hl>[cid:image001.jpg@01CE0F5F.BA92B690]<https://twitter.com/#!/StorageAssetMgt>[cid:image008.jpg@01CD76EE.8E8C0F10]<http://www.linkedin.com/company/storage-asset-management-inc>

**Comment by thiscouldbejd** [comment]
Hi Mickie,

Ok - great, thanks for letting me know...and glad it is working for you :)

Will close off this issue now, but if you have any questions in the future - don't hesitate to get in touch, and stay safe.

Yours,

JD.

**Comment by mmellottsam** [comment]
JD,

I just wanted to take a moment and thank you again for your assistance with my last questions and for also writing some so useful.
Our company has been using this for our remote in field users to submit trouble tickets for over two months now and it is working great.
I’ve been playing around with adding one extra features that I can not seem to get to work.  As I’m sure you know that more entries on the HELPDESK sheet the more scrolling down the sheet you need to do.  I was thinking if there would be a way on the Tracker menu to add another option called Last Row or Newest Ticket – that when clicked would move to the next row in Column A which contains a ticket number.

I’ve attempted to try my own code as well as a few different versions I’ve found online with no success.  So I thought I’d reach out and see if you have any suggestions.
Again, thank you for you time and any input you may have on this idea\suggestion.


Thanks,
Mickie


Mickiah Mellott, ADIT
IT Manager

[sam new logo - llc 2]
3501 Concord Road, Suite 350, York, PA 17402
Direct Office:  717-699-7041

www.StorageAssetManagement.com<http://www.storageassetmanagement.com/>
[cid:image003.jpg@01CE0F5F.BA92B690]<http://www.facebook.com/StorageAssetManagementInc?ref=hl>[cid:image001.jpg@01CE0F5F.BA92B690]<https://twitter.com/#!/StorageAssetMgt>[cid:image008.jpg@01CD76EE.8E8C0F10]<http://www.linkedin.com/company/storage-asset-management-inc>

From: Mickiah Mellott
Sent: Monday, March 23, 2020 10:30 AM
To: 'LifeStack-IO/lifestack-io.github.io' <reply@reply.github.com>; LifeStack-IO/lifestack-io.github.io <lifestack-io.github.io@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [LifeStack-IO/lifestack-io.github.io] Question on Ticket HASH (#2)

Hi JD,

Since I’ve copied all the ticket number manually, things seem to be working.  Possible glitch in Google sheets?!?
Thank you so much for your input – we think we will begin using this full time now.


Thanks,
Mickie


Mickiah Mellott, ADIT
IT Manager

[sam new logo - llc 2]
3501 Concord Road, Suite 350, York, PA 17402
Direct Office:  717-699-7041

www.StorageAssetManagement.com<http://www.storageassetmanagement.com/>
[cid:image003.jpg@01CE0F5F.BA92B690]<http://www.facebook.com/StorageAssetManagementInc?ref=hl>[cid:image001.jpg@01CE0F5F.BA92B690]<https://twitter.com/#!/StorageAssetMgt>[cid:image008.jpg@01CD76EE.8E8C0F10]<http://www.linkedin.com/company/storage-asset-management-inc>

**Comment by thiscouldbejd** [comment]
Hi Mickie,

Thanks for your kind words - and very glad you are finding it useful!

If I understand you correctly, I think the easiest solution to what you are trying to do is this:

1/ On the HELPDESK sheet, you need to change the formula in cell A6 to the following:

`=IFERROR(QUERY(QUERY(INDIRECT(ISSUES&"!R2C1:R1000C"&COUNTIF(QUERY(INDIRECT(ISSUES&"!R1", false), "select *"), "<>"), false), IF(STATUS = ALL, "select *", IF(STATUS = OPEN, "select * where B <> 'COMPLETE'", "select * where B = '"&STATUS&"'"))),"select * where Col1 is NOT NULL"),"")`

What this will do is basically restrict the list of tickets to ones which have values (this is a technical thing, but Sheets needs us to do this so the next bit of code works....)

2/ Open the Apps Script behind the sheet (Tools -> Script Editor) and open the 'Entry.gs' file.

In here, add the following two lines:

```
.addSeparator()
.addItem("Latest", "gotoLatest")
```

Straight after line 14 (e.g. after '.addItem("Show", "showSidebar")' and before '.addToUi();'.

This means your 'onOpen' function should read:

```
function onOpen() {

  var ui = SpreadsheetApp.getUi();
  ui.createMenu("Tracker")
      .addItem("Show", "showSidebar")
      .addSeparator()
      .addItem("Latest", "gotoLatest")
      .addToUi();
  
};
```

Then, add the following function at the bottom of that Entry.gs file:

```
function gotoLatest() {
  var sheet = SpreadsheetApp.getActiveSheet();
  if (sheet.getSheetName() == "HELPDESK") {
    SpreadsheetApp.getActive().setCurrentCell(sheet.getDataRange().getCell(sheet.getLastRow(), 1));
  }
}
```

What this will do is set the current selection (e.g. cursor position) to the end of the current 'DataRange' - which is defined in Sheets as the range which has values. As we changed our query expression in step 1 - the data range is now only as long as the number of tickets.

Save the Entry.gs file and reload the spreadsheet (e.g. refresh the browser tab). This is important as the entry code will only run on startup, so needs a reload to put the new menu item in.

Once it has reloaded, you should get an extra menu item that will take you to the latest ticket *provided you are already in the **HELPDESK** tab*.

Hope that helps - and let me know if it works or I have misunderstood what you needed!

Thanks,

JD.

**Comment by mmellottsam** [comment]
JD,

I apologize for not getting back to you sooner in regards to this code and question.
The code you provide does and does not work and this is what’s happening:  The code is moving the sheet, but for some reason, it’s moving it to the every bottom (row 1000) and the current new ticket is row 220.

Is there a way that you know of to search Column B (Status) for the word NEW or the color (conditional format) moving to the first cell in that column that meets criteria?  I think this might be a better approach?
Thank you for you assistance and input on this question\request.


Thanks,
Mickie


Mickiah Mellott, ADIT
IT Manager

[sam new logo - llc 2]
3501 Concord Road, Suite 350, York, PA 17402
Direct Office:  717-699-7041

www.StorageAssetManagement.com<http://www.storageassetmanagement.com/>
[cid:image003.jpg@01CE0F5F.BA92B690]<http://www.facebook.com/StorageAssetManagementInc?ref=hl>[cid:image001.jpg@01CE0F5F.BA92B690]<https://twitter.com/#!/StorageAssetMgt>[cid:image008.jpg@01CD76EE.8E8C0F10]<http://www.linkedin.com/company/storage-asset-management-inc>

**Comment by thiscouldbejd** [comment]
Hi,

Hope you are well!

It sounds like you might not have updated the formula in cell A6 on the HELPDESK sheet, as this will cause the behaviour you describe :)

If you would like the code to go to the last ticket that is 'NEW' - try using the following as the *gotoLatest* method (replace the function in the Entry.gs with this version):

```
function gotoLatest() {
  var sheet = SpreadsheetApp.getActiveSheet();
  if (sheet.getSheetName() == "HELPDESK") {
    var _data = sheet.getDataRange().getValues();
    var _last = _data.reduce(function(memo, row, index) {
      return row && row[1] && row[1] == "NEW" ? index : memo; 
    }, 0);
    SpreadsheetApp.getActive().setCurrentCell(sheet.getDataRange().getCell(_last + 1, 1));
  }
}
```

What we are doing here is looking for the last cell that has 'NEW' in the second column - and then going to that cell.

Hope that helps.

Yours,

JD

**Comment by mmellottsam** [comment]
JD,

Yes!  This has achieved exactly what we are looking for – thank you so much.

Thanks,
Mickie


Mickiah Mellott, ADIT
IT Manager

[sam new logo - llc 2]
3501 Concord Road, Suite 350, York, PA 17402
Direct Office:  717-699-7041

www.StorageAssetManagement.com<http://www.storageassetmanagement.com/>
[cid:image003.jpg@01CE0F5F.BA92B690]<http://www.facebook.com/StorageAssetManagementInc?ref=hl>[cid:image001.jpg@01CE0F5F.BA92B690]<https://twitter.com/#!/StorageAssetMgt>[cid:image008.jpg@01CD76EE.8E8C0F10]<http://www.linkedin.com/company/storage-asset-management-inc>

**Comment by thiscouldbejd** [comment]
Great - good to hear! Will close off this ticket but always feel free to get in touch if you need anything :)

**Comment by mmellottsam** [comment]
JD,

Thanks again for your help – your helpdesk sheet works really well.
I wanted to circle back and ask if there is away to determine the amount of time it’s taking to respond to ticket.  I’ve tried do some math and datedifs on the sheet, but it appears to change the lookups and is causing some issues.  Is this possible and something you’d know how to complete?


Thanks,
Mickie


Mickiah Mellott, ADIT
IT Manager

[sam new logo - llc 2]
3501 Concord Road, Suite 350, York, PA 17402
Direct Office:  717-699-7041

www.StorageAssetManagement.com<http://www.storageassetmanagement.com/>
***@***.******@***.******@***.***D750A6.36E15810]<http://www.linkedin.com/company/storage-asset-management-inc>

**Comment by thiscouldbejd** [comment]
Hi Mickie,

Nice to hear from you - and glad it is working well!

If depends a little bit on what you want to measure (e.g. do you want to include statistics about tickets you haven't yet responded to?). The way I would implement this would be as an additional tab in the sheet, that queries for tickets that have some response time on them. Then add in some additional columns to use DATEDIF (if you are happy with a resolution of just days) to get the difference between the opened date/time (TIMESTAMP) and the last updated date/time.

I have put together a basic tab showing this - and added it to my example sheet. You can grab it here:

https://docs.google.com/spreadsheets/d/1hheJ4nIUyiGADCcYr6f0bBRw6R362QwmMB4a5EMZVEo/copy

That should make a copy in your Google Drive, then right click on the 'Analysis' tab, and 'Copy to' and existing sheet (e.g. your 'live' helpdesk one). That should then give you something to work from! :)

Yours,

JD

**Comment by mmellottsam** [comment]
Thank you so much – that works as expected.


Thanks,
Mickie


Mickiah Mellott, ADIT
IT Manager

[sam new logo - llc 2]
3501 Concord Road, Suite 350, York, PA 17402
Direct Office:  717-699-7041

www.StorageAssetManagement.com<http://www.storageassetmanagement.com/>
***@***.******@***.******@***.***D75145.AAC17F40]<http://www.linkedin.com/company/storage-asset-management-inc>
